### ISSUE TITLE
Parser does not restart after logrotate

### ISSUE THREAD

**Issue by maximoalejandro** [NODO-UH/quota-scraper#12]
Parser 1.0 32bits get stuck on logrotate. If it is reloaded everything goes back to normal. Temporally i added a cron job to restart the parser at 7:00 AM

**Comment by adriantpaez** [comment]
I already fixed that in commit https://github.com/NODO-UH/quota-scraper/commit/6c0dc5b6c92b92884036bc36487fbff429615b05
